### ISSUE TITLE
No mac recovery entry 

### ISSUE THREAD

**Issue by nisel11** [tirpitzde/acer-an515-43_laptop_hackintosh-AMD#1]
I moved the EFI folder to the flash drive, also created com.apple.recovery.boot and put BaseSystem.dmg there along with BaseSystem.chunklist according to opencore instructions, but mac recovery is still missing.

**Comment by nisel11** [comment]
I solved it, but I have a question how did you install ventura? Through the big sur update or through the monterey recovery?

**Comment by tirpitzde** [comment]
Through the Bigsur update to Ventura. ^_^

**Comment by tirpitzde** [comment]
If you have two USB controllers, you need to disable one of them.

**Comment by nisel11** [comment]
> If you have two USB controllers, you need to disable one of them.

I bought a new flash drive and hope to be able to use this EFI with it. Can you know why I don't see anything other than ResetNVRam and ToggleSip?

**Comment by tirpitzde** [comment]
What's the configuration of your computer?发自我的手机-------- 原始邮件 --------发件人： nisel11 ***@***.***>日期： 2023年7月8日周六 21:34收件人： tirpitzde/acer-an515-43_laptop_hackintosh-AMD ***@***.***>抄送： tirpitzde ***@***.***>, Comment ***@***.***>主    题： Re: [tirpitzde/acer-an515-43_laptop_hackintosh-AMD] No mac recovery entry  (Issue #1)

If you have two USB controllers, you need to disable one of them.

I bought a new flash drive and hope to be able to use this EFI with it. Can you know why I don't see anything other than ResetNVRam and ToggleSip?

**Comment by nisel11** [comment]
Laptop Model	AN515-53 R7LU
Processor	AMD Ryzen 5 3550H
Graphics	Vega 8 & RX 560X
RAM	16GB DDR4-2666Mhz
Disk	Toshiba MQ04ABF100 1 TB
Audio	Realtek
Wifi	Qualcomm Atheros QCA6174
Ethernet	RealTek RTL8168/8111 PCI-E Gigabit Ethernet
Touchpad	Elan 0504

**Comment by nisel11** [comment]
> What's the configuration of your computer?发自我的手机-------- 原始邮件 --------发件人： nisel11 ***@***.***>日期： 2023年7月8日周六 21:34收件人： tirpitzde/acer-an515-43_laptop_hackintosh-AMD ***@***.***>抄送： tirpitzde ***@***.***>, Comment ***@***.***>主 题： Re: [tirpitzde/acer-an515-43_laptop_hackintosh-AMD] No mac recovery entry (Issue #1) If you have two USB controllers, you need to disable one of them. I bought a new flash drive and hope to be able to use this EFI with it. Can you know why I don't see anything other than ResetNVRam and ToggleSip? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Laptop Model	AN515-53 R7LU
Processor	AMD Ryzen 5 3550H
Graphics	Vega 8 & RX 560X
RAM	16GB DDR4-2666Mhz
Disk	Toshiba MQ04ABF100 1 TB
Audio	Realtek
Wifi	Qualcomm Atheros QCA6174
Ethernet	RealTek RTL8168/8111 PCI-E Gigabit Ethernet
Touchpad	Elan 0504

**Comment by tirpitzde** [comment]
The config.plist Misc→Security→ScanPolicy is set to 0发自我的手机

**Comment by tirpitzde** [comment]
ScanPolicy＝0发自我的手机-------- 原始邮件 --------发件人： nisel11 ***@***.***>日期： 2023年7月9日周日 19:25收件人： tirpitzde/acer-an515-43_laptop_hackintosh-AMD ***@***.***>抄送： tirpitzde ***@***.***>, Comment ***@***.***>主    题： Re: [tirpitzde/acer-an515-43_laptop_hackintosh-AMD] No mac recovery entry  (Issue #1)

What's the configuration of your computer?发自我的手机-------- 原始邮件 --------发件人： nisel11 @.>日期： 2023年7月8日周六 21:34收件人： tirpitzde/acer-an515-43_laptop_hackintosh-AMD @.>抄送： tirpitzde @.>, Comment @.>主 题： Re: [tirpitzde/acer-an515-43_laptop_hackintosh-AMD] No mac recovery entry (Issue #1) If you have two USB controllers, you need to disable one of them. I bought a new flash drive and hope to be able to use this EFI with it. Can you know why I don't see anything other than ResetNVRam and ToggleSip? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

Laptop Model	AN515-53 R7LU
Processor	AMD Ryzen 5 3550H
Graphics	Vega 8 & RX 560X
RAM	16GB DDR4-2666Mhz
Disk	Toshiba MQ04ABF100 1 TB
Audio	Realtek
Wifi	Qualcomm Atheros QCA6174
Ethernet	RealTek RTL8168/8111 PCI-E Gigabit Ethernet
Touchpad	Elan 0504

**Comment by nisel11** [comment]
> The config.plist Misc→Security→ScanPolicy is set to 0发自我的手机

Thank you very much, if I am not the only one with this problem I think this should be added to the README

**Comment by nisel11** [comment]
![IMG_20230711_184546_609](https://github.com/tirpitzde/acer-an515-43_laptop_hackintosh-AMD/assets/96194200/96923454-8ab9-4114-9418-430972b11e7f)
Hi, have you had this error? If so, can you tell me how you solved it?

**Comment by nisel11** [comment]
![IMG_20230711_184904_813](https://github.com/tirpitzde/acer-an515-43_laptop_hackintosh-AMD/assets/96194200/66f72eb4-ef5c-4c14-ab74-af952ece650b)
Hi, have you had this error? If so, can you tell me how you solved it?

**Comment by tirpitzde** [comment]
If you have two USB controllers, you need to disable one of them.

**Comment by tirpitzde** [comment]
And disable DSDT.aml,it for my laptop.
